# -*- coding: utf-8 -*-
"""Chest_X_Ray_Medical_Diagnosis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16i9AeKiEEys01g7H4gTV04G2OMXtClBN

# Chest X-Ray Medical Diagnosis with Deep Learning

<img src="xray-header-image.png" style="padding-top: 50px;width: 87%;left: 0px;margin-left: 0px;margin-right: 0px;">

In this notebook we will explore medical image diagnosis by building a state-of-the-art chest X-ray classifier using Keras.

In this notebook we will walk through some of the steps of building and evaluating this deep learning classifier model. In particular, we will:
- Pre-process and prepare a real-world X-ray dataset
- Use transfer learning to retrain a DenseNet model for X-ray image classification
- Learn a technique to handle class imbalance
- Measure diagnostic performance by computing the AUC (Area Under the Curve) for the ROC (Receiver Operating Characteristic) curve
- Visualize model activity using GradCAMs

## Outline
Use these links to jump to specific sections of this assignment!

- [1. Import Packages and Function](#1)
- [2. Load the Datasets](#2)
    - [2.1 Preventing Data Leakage](#2-1)
        - [Exercise 1 - Checking Data Leakage](#Ex-1)
    - [2.2 Preparing Images](#2-2)
- [3. Model Development](#3)
    - [3.1 Addressing Class Imbalance](#3-1)
        - [Exercise 2 - Computing Class Frequencies](#Ex-2)
        - [Exercise 3 - Weighted Loss](#Ex-3)
    - [3.3 DenseNet121](#3-3)
- [4. Training [optional]](#4)
    - [4.1 Training on the Larger Dataset](#4-1)
- [5. Prediction and Evaluation](#5)
    - [5.1 ROC Curve and AUROC](#5-1)
    - [5.2 Visualizing Learning with GradCAM](#5-2)

<a name='1'></a>
## 1. Import Packages and Functions¶

We'll make use of the following packages:
- `numpy` and `pandas` is what we'll use to manipulate our data
- `matplotlib.pyplot` and `seaborn` will be used to produce plots for visualization
- `util` will provide the locally defined utility functions that have been provided for this assignment

We will also use several modules from the `keras` framework for building deep learning models.
"""

!pip install keras

import os
print(os.listdir())

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras.applications.densenet import DenseNet121
from keras.layers import Dense, GlobalAveragePooling2D
from keras.models import Model
from keras import backend as K

from keras.models import load_model

import util

"""<a name='2'></a>
## 2 Load the Datasets

For this project, we will be using the [ChestX-ray8 dataset](https://arxiv.org/abs/1705.02315) which contains 108,948 frontal-view X-ray images of 32,717 unique patients.
- Each image in the data set contains multiple text-mined labels identifying 14 different pathological conditions.
- These in turn can be used by physicians to diagnose 8 different diseases.
- We will use this data to develop a single model that will provide binary classification predictions for each of the 14 labeled pathologies.
- In other words it will predict 'positive' or 'negative' for each of the pathologies.

You can download the entire dataset for free [here](https://nihcc.app.box.com/v/ChestXray-NIHCC).
- We have provided a ~1000 image subset of the images for you.
- These can be accessed in the folder path stored in the `IMAGE_DIR` variable.

The dataset includes a CSV file that provides the labels for each X-ray.

To make my job a bit easier, I have processed the labels for our small sample and generated three new files to get you started. These three files are:

1. `nih/train-small.csv`: 875 images from our dataset to be used for training.
1. `nih/valid-small.csv`: 109 images from our dataset to be used for validation.
1. `nih/test.csv`: 420 images from our dataset to be used for testing.

This dataset has been annotated by consensus among four different radiologists for 5 of our 14 pathologies:
- `Consolidation`
- `Edema`
- `Effusion`
- `Cardiomegaly`
- `Atelectasis`

#### Sidebar on meaning of 'class'
It is worth noting that the word **'class'** is used in multiple ways is these discussions.
- We sometimes refer to each of the 14 pathological conditions that are labeled in our dataset as a class.
- But for each of those pathologies we are attempting to predict whether a certain condition is present (i.e. positive result) or absent (i.e. negative result).
    - These two possible labels of 'positive' or 'negative' (or the numerical equivalent of 1 or 0) are also typically referred to as classes.
- Moreover, we also use the term in reference to software code 'classes' such as `ImageDataGenerator`.

As long as you are aware of all this though, it should not cause you any confusion as the term 'class' is usually clear from the context in which it is used.

#### Read in the data
Let's open these files using the [pandas](https://pandas.pydata.org/) library
"""

from google.colab import drive
drive.mount('/content/gdrive')

train_df = pd.read_csv("/content/train_set.csv")
valid_df = pd.read_csv("/content/valid_images.csv")

test_df = pd.read_csv("/content/test_set.csv")

train_df.head(100)

labels = ['Cardiomegaly',
          'Emphysema',
          'Effusion',
          'Hernia',
          'Infiltration',
          'Mass',
          'Nodule',
          'Atelectasis',
          'Pneumothorax',
          'Pleural_Thickening',
          'Pneumonia',
          'Fibrosis',
          'Edema',
          'Consolidation',
          'No Finding']

print("Sample data count :")
count = 0
for label in labels:
    count += train_df['Findings'].value_counts()[1]
    print(f"There are {train_df['Findings'].value_counts()[1]} samples of disease {label}.")

print(f"There are {count} samples of disease.")
noData = len(train_df["Patient ID"]) - count
print(f"There are {noData} samples of no disease.")

"""<a name='2-1'></a>
### 2.1 Preventing Data Leakage
It is worth noting that our dataset contains multiple images for each patient. This could be the case, for example, when a patient has taken multiple X-ray images at different times during their hospital visits. In our data splitting, we have ensured that the split is done on the patient level so that there is no data "leakage" between the train, validation, and test datasets.

<a name='Ex-1'></a>
#### Checking Data Leakage
In the cell below, write a function to check whether there is leakage between two datasets. We'll use this to make sure there are no patients in the test set that are also present in either the train or validation sets.
"""

def check_for_leakage(df1, df2, patient_col):
    """
    Return True if there any patients are in both df1 and df2.

    Args:
        df1 (dataframe): dataframe describing first dataset
        df2 (dataframe): dataframe describing second dataset
        patient_col (str): string name of column with patient IDs

    Returns:
        leakage (bool): True if there is leakage, otherwise False
    """
    #Converting datalist into frame to get unique patient IDs
    df1_patients_unique = set(df1[patient_col])
    df2_patients_unique = set(df2[patient_col])

    #Finding the intersection of both sets to check for leakage
    patients_in_both_groups = list(df1_patients_unique.intersection(df2_patients_unique))

    # leakage contains true if there is patient overlap, otherwise false.
    leakage = True if len(patients_in_both_groups) > 0 else False  # boolean (true if there is at least 1 patient in both groups)

    return leakage

# test for check_for_leakage()
print("test case 1")
df1 = pd.DataFrame({'patient_id': [0, 1, 2]})
df2 = pd.DataFrame({'patient_id': [2, 3, 4]})
print("df1")
print(df1)
print("df2")
print(df2)
print(f"leakage output: {check_for_leakage(df1, df2, 'patient_id')}")
print("-------------------------------------")
print("test case 2")
df1 = pd.DataFrame({'patient_id': [0, 1, 2]})
df2 = pd.DataFrame({'patient_id': [3, 4, 5]})
print("df1:")
print(df1)
print("df2:")
print(df2)

print(f"leakage output: {check_for_leakage(df1, df2, 'patient_id')}")

"""The next cell is run to check if there are patients in both train and test or in both valid and test."""

print("leakage between train and test: {}".format(check_for_leakage(train_df, test_df, 'Patient ID')))
print("leakage between valid and test: {}".format(check_for_leakage(valid_df, test_df, 'Patient ID')))

"""If we get `False` for both, then we're ready to start preparing the datasets for training. Remember to always check for data leakage!

<a name='2-2'></a>
### 2.2 Preparing Images

With our dataset splits ready, we can now proceed with setting up our model to consume them.
- For this we will use the off-the-shelf [ImageDataGenerator](https://keras.io/preprocessing/image/) class from the Keras framework, which allows us to build a "generator" for images specified in a dataframe.
- This class also provides support for basic data augmentation such as random horizontal flipping of images.
- We also use the generator to transform the values in each batch so that their mean is $0$ and their standard deviation is 1.
    - This will facilitate model training by standardizing the input distribution.
- The generator also converts our single channel X-ray images (gray-scale) to a three-channel format by repeating the values in the image across all channels.
    - We will want this because the pre-trained model that we'll use requires three-channel inputs.

I have implemented the following using the generator:
1. Normalize the mean and standard deviation of the data
3. Shuffle the input after each epoch.
4. Set the image size to be 320px by 320px
"""

def get_train_generator(df, image_dir, x_col, y_cols, shuffle=True, batch_size=8, seed=1, target_w = 320, target_h = 320):
    """
    Return generator for training set, normalizing using batch
    statistics.

    Args:
      train_df (dataframe): dataframe specifying training data.
      image_dir (str): directory where image files are held.
      x_col (str): name of column in df that holds filenames.
      y_cols (list): list of strings that hold y labels for images.
      batch_size (int): images per batch to be fed into model during training.
      seed (int): random seed.
      target_w (int): final width of input images.
      target_h (int): final height of input images.

    Returns:
        train_generator (DataFrameIterator): iterator over training set
    """
    print("getting train generator...")
    # normalize images
    image_generator = ImageDataGenerator(
        samplewise_center=True,
        samplewise_std_normalization= True)

    # flow from directory with specified batch size
    # and target image size
    generator = image_generator.flow_from_dataframe(
            dataframe=df,
            directory=image_dir,
            x_col=x_col,
            y_col=y_cols,
            class_mode="raw",
            batch_size=batch_size,
            shuffle=shuffle,
            seed=seed,
            target_size=(target_w,target_h))


    # First, check what's in your y_cols
    print(train_df[y_cols].dtypes)

    # If they're strings, you need to convert them to numeric values
    from sklearn.preprocessing import LabelEncoder

    # If you have a single label column
    if isinstance(y_cols, str):
      label_encoder = LabelEncoder()
      train_df['encoded_label'] = label_encoder.fit_transform(train_df[y_cols])
      valid_df['encoded_label'] = label_encoder.transform(valid_df[y_cols])
      test_df['encoded_label'] = label_encoder.transform(test_df[y_cols])

      # Save the mapping for later reference
      label_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
      print("Label mapping:", label_mapping)

    # Update your generator to use the encoded labels
      y_cols = 'encoded_label'

  # If you have multiple label columns
    else:
      for col in y_cols:
        if train_df[col].dtype == 'object':  # If it's string data
            train_df[col] = train_df[col].astype(float)
            valid_df[col] = valid_df[col].astype(float)
            test_df[col] = test_df[col].astype(float)


    return generator

"""#### Build a separate generator for valid and test sets

Now we need to build a new generator for validation and testing data.

**Why can't we use the same generator as for the training data?**

Look back at the generator we wrote for the training data.
- It normalizes each image **per batch**, meaning that it uses batch statistics.
- We should not do this with the test and validation data, since in a real life scenario we don't process incoming images a batch at a time (we process one image at a time).
- Knowing the average per batch of test data would effectively give our model an advantage.  
    - The model should not have any information about the test data.

What we need to do is normalize incoming test data using the statistics **computed from the training set**.
* We implement this in the function below.
* There is one technical note. Ideally, we would want to compute our sample mean and standard deviation using the entire training set.
* However, since this is extremely large, that would be very time consuming.
* In the interest of time, we'll take a random sample of the dataset and calcualte the sample mean and sample standard deviation.
"""

def get_test_and_valid_generator(valid_df, test_df, train_df, image_dir, x_col, y_cols, sample_size=100, batch_size=8, seed=1, target_w = 320, target_h = 320):
    """
    Return generator for validation set and test test set using
    normalization statistics from training set.

    Args:
      valid_df (dataframe): dataframe specifying validation data.
      test_df (dataframe): dataframe specifying test data.
      train_df (dataframe): dataframe specifying training data.
      image_dir (str): directory where image files are held.
      x_col (str): name of column in df that holds filenames.
      y_cols (list): list of strings that hold y labels for images.
      sample_size (int): size of sample to use for normalization statistics.
      batch_size (int): images per batch to be fed into model during training.
      seed (int): random seed.
      target_w (int): final width of input images.
      target_h (int): final height of input images.

    Returns:
        test_generator (DataFrameIterator) and valid_generator: iterators over test set and validation set respectively
    """
    print("getting train and valid generators...")
    # get generator to sample dataset
    raw_train_generator = ImageDataGenerator().flow_from_dataframe(
        dataframe=train_df,
        directory=IMAGE_DIR,
        x_col=x_col,
        y_col=y_cols,
        class_mode="raw",
        batch_size=sample_size,
        shuffle=True,
        target_size=(target_w, target_h))

    # get data sample
    #batch = raw_train_generator.next()
    batch = next(raw_train_generator)
    data_sample = batch[0]

    # use sample to fit mean and std for test set generator
    image_generator = ImageDataGenerator(
        featurewise_center=True,
        featurewise_std_normalization= True)

    # fit generator to sample from training data
    image_generator.fit(data_sample)

    # get test generator
    valid_generator = image_generator.flow_from_dataframe(
            dataframe=valid_df,
            directory=image_dir,
            x_col=x_col,
            y_col=y_cols,
            class_mode="raw",
            batch_size=batch_size,
            shuffle=False,
            seed=seed,
            target_size=(target_w,target_h))

    test_generator = image_generator.flow_from_dataframe(
            dataframe=test_df,
            directory=image_dir,
            x_col=x_col,
            y_col=y_cols,
            class_mode="raw",
            batch_size=batch_size,
            shuffle=False,
            seed=seed,
            target_size=(target_w,target_h))
    return valid_generator, test_generator

"""With our generator function ready, let's make one generator for our training data and one each of our test and  validation datasets."""

IMAGE_DIR = "/content/gdrive/MyDrive/XDC_Ramya/Sample_Images"
train_generator = get_train_generator(train_df, IMAGE_DIR, "New Image Index", 'Findings')
valid_generator, test_generator= get_test_and_valid_generator(valid_df, test_df, train_df, IMAGE_DIR, "New Image Index", 'Findings')

"""Let's peek into what the generator gives our model during training and validation. We can do this by calling the `__get_item__(index)` function:"""

x, y = train_generator.__getitem__(0)
plt.imshow(x[0]);

"""<a name='3'></a>
## 3 Model Development

Now we'll move on to model training and development. We have a few practical challenges to deal with before actually training a neural network, though. The first is class imbalance.

<a name='3-1'></a>
### 3.1 Addressing Class Imbalance
One of the challenges with working with medical diagnostic datasets is the large class imbalance present in such datasets. Let's plot the frequency of each of the labels in our dataset:
"""

print(type(train_generator.labels))
print(train_generator.labels.shape if hasattr(train_generator.labels, 'shape') else len(train_generator.labels))
print(train_generator.labels[:20])  # Print first 5 elements to see structure

import pandas as pd

# Assuming train_df is your original dataframe
# And 'Findings' is your label column
label_counts = train_df['Findings'].value_counts()

plt.figure(figsize=(12, 6))
plt.xticks(rotation=90)
plt.bar(x=label_counts.index, height=label_counts.values)
plt.title("Frequency of Each Class")
plt.tight_layout()
plt.show()

"""We can see from this plot that the prevalance of positive cases varies significantly across the different pathologies. (These trends mirror the ones in the full dataset as well.)
* The `Hernia` pathology has the greatest imbalance with the proportion of positive training cases being about 0.2%.
* But even the `Infiltration` pathology, which has the least amount of imbalance, has only 17.5% of the training cases labelled positive.

Ideally, we would train our model using an evenly balanced dataset so that the positive and negative training cases would contribute equally to the loss.

If we use a normal cross-entropy loss function with a highly unbalanced dataset, as we are seeing here, then the algorithm will be incentivized to prioritize the majority class (i.e negative in our case), since it contributes more to the loss.

#### Impact of class imbalance on loss function

Let's take a closer look at this. Assume we would have used a normal cross-entropy loss for each pathology. We recall that the cross-entropy loss contribution from the $i^{th}$ training data case is:

$$\mathcal{L}_{cross-entropy}(x_i) = -(y_i \log(f(x_i)) + (1-y_i) \log(1-f(x_i))),$$

where $x_i$ and $y_i$ are the input features and the label, and $f(x_i)$ is the output of the model, i.e. the probability that it is positive.

Note that for any training case, either $y_i=0$ or else $(1-y_i)=0$, so only one of these terms contributes to the loss (the other term is multiplied by zero, and becomes zero).

We can rewrite the overall average cross-entropy loss over the entire training set $\mathcal{D}$ of size $N$ as follows:

$$\mathcal{L}_{cross-entropy}(\mathcal{D}) = - \frac{1}{N}\big( \sum_{\text{positive examples}} \log (f(x_i)) + \sum_{\text{negative examples}} \log(1-f(x_i)) \big).$$

Using this formulation, we can see that if there is a large imbalance with very few positive training cases, for example, then the loss will be dominated by the negative class. Summing the contribution over all the training cases for each class (i.e. pathological condition), we see that the contribution of each class (i.e. positive or negative) is:

$$freq_{p} = \frac{\text{number of positive examples}}{N} $$

$$\text{and}$$

$$freq_{n} = \frac{\text{number of negative examples}}{N}.$$

<a name='Ex-2'></a>
### Computing Class Frequencies
The function below calculates the frequences for each label in our dataset.
"""

def compute_class_freqs(labels):
    """
    Compute positive and negative frequences for each class.

    Args:
        labels (np.array): matrix of labels, size (num_examples, num_classes)
    Returns:
        positive_frequencies (np.array): array of positive frequences for each
                                         class, size (num_classes)
        negative_frequencies (np.array): array of negative frequences for each
                                         class, size (num_classes)
    """
    # total number of patients (rows)
    N = labels.shape[0]

    positive_frequencies = np.sum(labels, axis = 0) / N
    negative_frequencies = 1 - positive_frequencies

    return positive_frequencies, negative_frequencies

# Test compute_class_freqs()
labels_matrix = np.array(
    [[1, 0, 0],
     [0, 1, 1],
     [1, 0, 1],
     [1, 1, 1],
     [1, 0, 1]]
)
print("labels:")

test_pos_freqs, test_neg_freqs = compute_class_freqs(labels_matrix)

print(f"pos freqs: {test_pos_freqs}")

print(f"neg freqs: {test_neg_freqs}")

"""Now we'll compute frequencies for our training data."""

def compute_class_freqs(labels):
    """
    Compute positive and negative frequencies for each class.

    Args:
        labels (numpy.ndarray): matrix of labels, size (samples, classes)

    Returns:
        positive_frequencies (numpy.ndarray): array of positive frequencies for each class
        negative_frequencies (numpy.ndarray): array of negative frequencies for each class
    """
    # Convert string labels to numeric format if needed
    if isinstance(labels[0], str):
        # For multi-label case separated by some delimiter like '|'
        unique_classes = set()
        for label_str in labels:
            classes = label_str.split('|')  # Adjust delimiter as needed
            for cls in classes:
                unique_classes.add(cls.strip())

        unique_classes = sorted(list(unique_classes))

        # Create one-hot encoding
        N = len(labels)
        C = len(unique_classes)
        numeric_labels = np.zeros((N, C))

        class_to_idx = {cls: i for i, cls in enumerate(unique_classes)}

        for i, label_str in enumerate(labels):
            classes = label_str.split('|')  # Adjust delimiter as needed
            for cls in classes:
                cls = cls.strip()
                if cls:  # Skip empty strings
                    numeric_labels[i, class_to_idx[cls]] = 1

        labels = numeric_labels

    # Now compute frequencies
    N = labels.shape[0]
    positive_frequencies = np.sum(labels, axis=0) / N
    negative_frequencies = 1 - positive_frequencies

    return positive_frequencies, negative_frequencies

# If your labels are single class per sample
if isinstance(train_generator.labels[0], str):
    from sklearn.preprocessing import LabelBinarizer
    lb = LabelBinarizer()
    numeric_labels = lb.fit_transform(train_generator.labels)
    freq_pos, freq_neg = compute_class_freqs(numeric_labels)
else:
    freq_pos, freq_neg = compute_class_freqs(train_generator.labels)

freq_pos, freq_neg = compute_class_freqs(train_generator.labels)
freq_pos

"""Let's visualize these two contribution ratios next to each other for each of the pathologies:"""

# First, create the positive data frame
positive_df = pd.DataFrame({
    "Class": labels,
    "Label": "Positive",
    "Value": freq_pos
})

# Then create the negative data frame
negative_data = []
for l, v in enumerate(freq_neg):
    negative_data.append({
        "Class": labels[l],
        "Label": "Negative",
        "Value": v
    })
negative_df = pd.DataFrame(negative_data)

# Now concatenate the two dataframes
data = pd.concat([positive_df, negative_df], ignore_index=True)

# Plot
plt.figure(figsize=(12, 6))
plt.xticks(rotation=90)
sns.barplot(x="Class", y="Value", hue="Label", data=data)
plt.tight_layout()
plt.show()

"""As we see in the above plot, the contributions of positive cases is significantly lower than that of the negative ones. However, we want the contributions to be equal. One way of doing this is by multiplying each example from each class by a class-specific weight factor, $w_{pos}$ and $w_{neg}$, so that the overall contribution of each class is the same.

To have this, we want

$$w_{pos} \times freq_{p} = w_{neg} \times freq_{n},$$

which we can do simply by taking

$$w_{pos} = freq_{neg}$$
$$w_{neg} = freq_{pos}$$

This way, we will be balancing the contribution of positive and negative labels.
"""

pos_weights = freq_neg
neg_weights = freq_pos
pos_contribution = freq_pos * pos_weights
neg_contribution = freq_neg * neg_weights

"""Let's verify this by graphing the two contributions next to each other again:"""

# Create the initial dataframe with positive values
data = pd.DataFrame({
    "Class": labels,
    "Label": "Positive",
    "Value": pos_contribution
})

# Create a list of dictionaries for negative values
neg_data = [
    {"Class": labels[l], "Label": "Negative", "Value": v}
    for l, v in enumerate(neg_contribution)
]

# Create a DataFrame from the list of dictionaries
neg_df = pd.DataFrame(neg_data)

# Concatenate the two DataFrames
data = pd.concat([data, neg_df], ignore_index=True)

# Plot
plt.xticks(rotation=90)
sns.barplot(x="Class", y="Value", hue="Label", data=data)

"""As the above figure shows, by applying these weightings the positive and negative labels within each class would have the same aggregate contribution to the loss function. Now let's implement such a loss function.

After computing the weights, our final weighted loss for each training case will be

$$\mathcal{L}_{cross-entropy}^{w}(x) = - (w_{p} y \log(f(x)) + w_{n}(1-y) \log( 1 - f(x) ) ).$$

<a name='Ex-3'></a>
### Weighted Loss
The `weighted_loss` function below returns a loss function that calculates the weighted loss for each batch. Note that we also want to add a small value, $\epsilon$, to the predicted values before taking their logs. This is simply to avoid a numerical error that would otherwise occur if the predicted value happens to be zero.
"""

def get_weighted_loss(pos_weights, neg_weights, epsilon=1e-7):
    """
    Return weighted loss function given negative weights and positive weights.

    Args:
      pos_weights (np.array): array of positive weights for each class, size (num_classes)
      neg_weights (np.array): array of negative weights for each class, size (num_classes)

    Returns:
      weighted_loss (function): weighted loss function
    """
    def weighted_loss(y_true, y_pred):
        """
        Return weighted loss value.

        Args:
            y_true (Tensor): Tensor of true labels, size is (num_examples, num_classes)
            y_pred (Tensor): Tensor of predicted labels, size is (num_examples, num_classes)
        Returns:
            loss (Float): overall scalar loss summed across all classes
        """
        # initialize loss to zero
        loss = 0.0

        for i in range(len(pos_weights)):
            # for each class, we add average weighted loss for that class
            pos_loss = -1 * tf.reduce_mean(pos_weights[i] * y_true[:, i] * tf.math.log(y_pred[:, i] + epsilon))
            neg_loss = -1 * tf.reduce_mean(neg_weights[i] * (1 - y_true[:, i]) * tf.math.log(1 - y_pred[:, i] + epsilon))
            loss += pos_loss + neg_loss
        return loss

        ### END CODE HERE ###
    return weighted_loss

"""Now let's test our function with some simple cases."""

import tensorflow as tf
import numpy as np
from tensorflow import keras
import keras.backend as K

# Assuming get_weighted_loss is defined somewhere

# Test get_weighted_loss() - Updated for TF 2.x
# Create tensors directly with tf
print("Test example:\n")
y_true = tf.constant(np.array(
    [[1, 1, 1],
     [1, 1, 0],
     [0, 1, 0],
     [1, 0, 1]]
), dtype=tf.float32)
print("y_true:\n")
print(y_true.numpy())

w_p = np.array([0.25, 0.25, 0.5])
w_n = np.array([0.75, 0.75, 0.5])
print("\nw_p:\n")
print(w_p)

print("\nw_n:\n")
print(w_n)

y_pred_1 = tf.constant(0.7*np.ones(y_true.shape), dtype=tf.float32)
print("\ny_pred_1:\n")
print(y_pred_1.numpy())

y_pred_2 = tf.constant(0.3*np.ones(y_true.shape), dtype=tf.float32)
print("\ny_pred_2:\n")
print(y_pred_2.numpy())

# test with a large epsilon in order to catch errors
L = get_weighted_loss(w_p, w_n, epsilon=1)

print("\nIf we weighted them correctly, we expect the two losses to be the same.")
L1 = L(y_true, y_pred_1).numpy()
L2 = L(y_true, y_pred_2).numpy()
print(f"\nL(y_pred_1)= {L1:.4f}, L(y_pred_2)= {L2:.4f}")
print(f"Difference is L1 - L2 = {L1 - L2:.4f}")

"""<a name='3-3'></a>
### 3.3 DenseNet121

Next, we will use a pre-trained [DenseNet121](https://www.kaggle.com/pytorch/densenet121) model which we can load directly from Keras and then add two layers on top of it:
1. A `GlobalAveragePooling2D` layer to get the average of the last convolution layers from DenseNet121.
2. A `Dense` layer with `sigmoid` activation to get the prediction logits for each of our classes.

We can set our custom loss function for the model by specifying the `loss` parameter in the `compile()` function.
"""

# create the base pre-trained model
base_model = DenseNet121(weights='imagenet', include_top=False)
#base_model = DenseNet121(weights='/content/densenet.hdf5', include_top=False)

x = base_model.output

# add a global spatial average pooling layer
x = GlobalAveragePooling2D()(x)

# and a logistic layer
predictions = Dense(len(labels), activation="sigmoid")(x)

model = Model(inputs=base_model.input, outputs=predictions)
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')
#model.compile(optimizer='adam', loss=get_weighted_loss(pos_weights, neg_weights))

# Add this before training to check data types
batch_x, batch_y = next(train_generator)
print("X shape:", batch_x.shape, "X dtype:", batch_x.dtype)
print("Y shape:", batch_y.shape, "Y dtype:", batch_y.dtype)

# If batch_y is object dtype, convert it
if batch_y.dtype == 'object':
    print("Converting Y to float32")
    # Sample of the data to understand what's in it
    print("Sample Y data:", batch_y[:20])

# Convert string labels to numeric indices
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
train_df['Findings_encoded'] = label_encoder.fit_transform(train_df['Findings'])

# Get the number of unique classes
num_classes = len(np.unique(train_df['Findings_encoded']))

# Update your model
predictions = Dense(num_classes, activation="softmax")(x)
model = Model(inputs=base_model.input, outputs=predictions)
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')

# Make sure your generators are providing numeric labels
# If using ImageDataGenerator, you may need to set class_mode='sparse'

# Change your model setup
predictions = Dense(len(np.unique(train_df['Findings'])), activation="softmax")(x)
model = Model(inputs=base_model.input, outputs=predictions)
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')

# Update your model architecture for multi-label classification
num_classes = len('Findings')  # Number of possible conditions

# Modify the output layer for multi-label classification
x = base_model.output
x = GlobalAveragePooling2D()(x)
predictions = Dense(num_classes, activation="sigmoid")(x)  # Use sigmoid for multi-label

model = Model(inputs=base_model.input, outputs=predictions)

# Binary crossentropy for multi-label classification
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Update your model architecture for multi-label classification
# ... (rest of your model definition)

# Convert labels to numeric format before fitting the model
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Assuming your labels are in a column called 'Findings'
label_encoder = LabelEncoder()
all_labels = np.concatenate([train_df['Findings'], valid_df['Findings'], test_df['Findings']])
label_encoder.fit(all_labels)  # Fit on all labels to ensure all classes are encoded

train_df['Findings_encoded'] = label_encoder.transform(train_df['Findings'])
valid_df['Findings_encoded'] = label_encoder.transform(valid_df['Findings'])
test_df['Findings_encoded'] = label_encoder.transform(test_df['Findings'])

# Update your generators to use the encoded labels
train_generator = get_train_generator(train_df, IMAGE_DIR, "New Image Index", 'Findings_encoded')
valid_generator, test_generator = get_test_and_valid_generator(valid_df, test_df, train_df, IMAGE_DIR, "New Image Index", 'Findings_encoded')

# Now you can fit the model
history = model.fit(train_generator,
                    validation_data=valid_generator,
                    steps_per_epoch=100,
                    validation_steps=25,
                    epochs=3)

# ... (rest of your code)

history = model.fit(train_generator,
                              validation_data=valid_generator,
                              steps_per_epoch=100,
                              validation_steps=25,
                              epochs = 3)

plt.plot(history.history['loss'])
plt.ylabel("loss")
plt.xlabel("epoch")
plt.title("Training Loss Curve")
plt.show()

"""<a name='4'></a>
## 4 Training

With our model ready for training, we will use the `model.fit()` function in Keras to train our model.
- We are training on a small subset of the dataset (~1%).  
- So what we care about at this point is to make sure that the loss on the training set is decreasing.

Since training can take a considerable time, for pedagogical purposes I have chosen not to train the model here but rather to load a set of pre-trained weights in the next section which was trained in Colab.

Python Code for training the model:

```python
history = model.fit_generator(train_generator,
                              validation_data=valid_generator,
                              steps_per_epoch=100,
                              validation_steps=25,
                              epochs = 3)

plt.plot(history.history['loss'])
plt.ylabel("loss")
plt.xlabel("epoch")
plt.title("Training Loss Curve")
plt.show()
```

<a name='4-1'></a>
### 4.1 Training on the Larger Dataset

Given that the original dataset is 40GB+ in size and the training process on the full dataset takes a few hours, we have trained the model on a GPU-equipped machine for you and provided the weights file from our model (with a batch size of 32 instead) to be used for the rest of this assignment.

The model architecture for our pre-trained model is exactly the same, but we used a few useful Keras "callbacks" for this training. Do spend time to read about these callbacks at your leisure as they will be very useful for managing long-running training sessions:

1. You can use `ModelCheckpoint` callback to monitor your model's `val_loss` metric and keep a snapshot of your model at the point.
2. You can use the `TensorBoard` to use the Tensorflow Tensorboard utility to monitor your runs in real-time.
3. You can use the `ReduceLROnPlateau` to slowly decay the learning rate for your model as it stops getting better on a metric such as `val_loss` to fine-tune the model in the final steps of training.
4. You can use the `EarlyStopping` callback to stop the training job when your model stops getting better in it's validation loss. You can set a `patience` value which is the number of epochs the model does not improve after which the training is terminated. This callback can also conveniently restore the weights for the best metric at the end of training to your model.

You can read about these callbacks and other useful Keras callbacks [here](https://keras.io/callbacks/).

Let's load our pre-trained weights into the model now:
"""

model.load_weights("./nih/pretrained_model.h5")

"""<a name='5'></a>
## 5 Prediction and Evaluation

Now that we have a model, let's evaluate it using our test set. We can conveniently use the `predict_generator` function to generate the predictions for the images in our test set.

**Note:** The following cell can take about 4 minutes to run.
"""

predicted_vals = model.predict_generator(test_generator, steps = len(test_generator))

"""<a name='5-1'></a>
### 5.1 ROC Curve and AUROC
To evaluate my model I use a metric called the AUC (Area Under the Curve) from the ROC ([Receiver Operating Characteristic](https://en.wikipedia.org/wiki/Receiver_operating_characteristic)) curve. This is also referred to as the AUROC value.

We will use the `util.get_roc_curve()` function which has been provided for you in `util.py`. Look through this function and note the use of the `sklearn` library functions to generate the ROC curves and AUROC values for our model.

- [roc_curve](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_curve.html)
- [roc_auc_score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html)
"""

auc_rocs = util.get_roc_curve(labels, predicted_vals, test_generator)

"""You can compare the performance to the AUCs reported in the original ChexNeXt paper in the table below:

For reference, here's the AUC figure from the ChexNeXt paper which includes AUC values for their model as well as radiologists on this dataset:

<img src="https://journals.plos.org/plosmedicine/article/figure/image?size=large&id=10.1371/journal.pmed.1002686.t001" width="80%">

This method does take advantage of a few other tricks such as self-training and ensembling as well, which can give a significant boost to the performance.

For details about the best performing methods and their performance on this dataset, we encourage you to read the following papers:
- [CheXNet](https://arxiv.org/abs/1711.05225)
- [CheXpert](https://arxiv.org/pdf/1901.07031.pdf)
- [ChexNeXt](https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1002686)

<a name='5-2'></a>
### 5.2 Visualizing Learning with GradCAM

One of the challenges of using deep learning in medicine is that the complex architecture used for neural networks makes them much harder to interpret compared to traditional machine learning models (e.g. linear models).

One of the most common approaches aimed at increasing the interpretability of models for computer vision tasks is to use Class Activation Maps (CAM).
- Class activation maps are useful for understanding where the model is "looking" when classifying an image.

In this section we will use a [GradCAM's](https://arxiv.org/abs/1610.02391) technique to produce a heatmap highlighting the important regions in the image for predicting the pathological condition.
- This is done by extracting the gradients of each predicted class, flowing into our model's final convolutional layer. Look at the `util.compute_gradcam` which has been provided for you in `util.py` to see how this is done with the Keras framework.

It is worth mentioning that GradCAM does not provide a full explanation of the reasoning for each classification probability.
- However, it is still a useful tool for "debugging" our model and augmenting our prediction so that an expert could validate that a prediction is indeed due to the model focusing on the right regions of the image.

First we will load the small training set and setup to look at the 4 classes with the highest performing AUC measures.
"""

df = pd.read_csv("nih/train-small.csv")
IMAGE_DIR = "nih/images-small/"

# only show the lables with top 4 AUC
labels_to_show = np.take(labels, np.argsort(auc_rocs)[::-1])[:4]

"""Now let's look at a few specific images."""

util.compute_gradcam(model, '00008270_015.png', IMAGE_DIR, df, labels, labels_to_show)

util.compute_gradcam(model, '00011355_002.png', IMAGE_DIR, df, labels, labels_to_show)

util.compute_gradcam(model, '00029855_001.png', IMAGE_DIR, df, labels, labels_to_show)

util.compute_gradcam(model, '00005410_000.png', IMAGE_DIR, df, labels, labels_to_show)

"""<a name='5-2'></a>
### With this we complete the Chest X-Ray Medical Diagnosis with Deep Learning Project!
"""